//! This file is autogenerated by build.rs, do not edit.
#![cfg_attr(rustfmt, rustfmt_skip)]

pub mod reporting;
pub mod tags;
pub mod moderation;

pub fn get_all_commands() -> Vec<poise::Command<crate::Data, crate::Error>> {
	vec![reporting::report_message::report_message(), reporting::report_user::report_user(), tags::dtag::dtag(), tags::tag::tag(), moderation::unban::unban(), moderation::dban::dban(), moderation::warn::warn(), moderation::mute::mute(), moderation::ban::ban(), moderation::kick::kick()]
}