//! This file is autogenerated by build.rs, do not edit.
#![cfg_attr(rustfmt, rustfmt_skip)]

pub mod moderation;
pub mod reporting;
pub mod tags;

pub fn get_all_commands() -> Vec<poise::Command<crate::Data, crate::Error>> {
	vec![moderation::ban::ban(), moderation::dban::dban(), moderation::kick::kick(), moderation::mute::mute(), moderation::unban::unban(), moderation::warn::warn(), reporting::report_message::report_message(), reporting::report_user::report_user(), tags::dtag::dtag(), tags::tag::tag()]
}