[profile.dev]
opt-level = 0
incremental = true

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true

[workspace]
members = ["crates/bot", "crates/api"]
resolver = "3"
