#![cfg_attr(rustfmt, rustfmt_skip)]
// This file is autogenerated by build.rs, do not edit.

pub mod reporting;
pub mod test;

pub fn get_all_commands() -> Vec<poise::Command<crate::Data, crate::types::Error>> {
    vec![
		reporting::report_user_command::report_user(), 
		test::test_command::test()]
}