//! This file is autogenerated by build.rs, do not edit.
#![cfg_attr(rustfmt, rustfmt_skip)]

pub mod reporting;

pub fn get_all_commands() -> Vec<poise::Command<crate::Data, crate::types::Error>> {
    vec![reporting::report_message_command::report_message(), reporting::report_user_command::report_user()]
}