[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]

axum = "0.8.4"
tokio = { version = "1.45.0", features = ["full"] }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

sled = "0.34.7"

tracing-subscriber = "0.3.19"
tracing = "0.1.41"
