//! This file is autogenerated by build.rs, do not edit.
#![cfg_attr(rustfmt, rustfmt_skip)]

pub mod guild_id;

pub use axum::Router;

pub fn add_endpoints(app: Router) -> Router {
	app.merge(guild_id::test_endpoint::test())
}